apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: expense-tracker
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: YourStrongPassword123!
  MONGO_URI: mongodb://admin:YourStrongPassword123!@mongodb-svc:27017/expensedb?authSource=admin