apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: expense-tracker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2          # default EKS storage class, backed by EBS
  resources:
    requests:
      storage: 5Gi