apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense-tracker
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: oghenetejiri798/expense-tracker-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI           # ✅ now correctly under env
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"